debug: true

messages:
  prefix: '<dark_gray>[<color:#FFEE8C>ᴠᴀʟᴇʀɪɴ<dark_gray>]<reset> '
  no-permission: '%prefix%<red>No tienes permiso para usar este comando.'
  only-players: '%prefix%<red>Solo jugadores pueden usar este comando.'
  valerinutils-usage: '%prefix%<gray>Uso: <yellow>/valerinutils reload'
  valerinutils-reload-ok: '%prefix%<green>Configuración y módulos recargados correctamente.'
  
database:
  # sqlite is the only optimized option for now
  type: sqlite
